import * as THREE from 'three';
const renderer = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true });
renderer.setSize(300, 300);
document.body.appendChild(renderer.domElement);
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x6ec6ff);
const cam = new THREE.PerspectiveCamera(60, 1, 0.1, 100);
cam.position.set(2, 2, 3); cam.lookAt(0, 0, 0);
const light = new THREE.DirectionalLight(0xffffff, 1); light.position.set(3, 5, 2); scene.add(light);
scene.add(new THREE.AmbientLight(0xffffff, 0.5));
const cube = new THREE.Mesh(new THREE.BoxGeometry(1.5, 1.5, 1.5), new THREE.MeshStandardMaterial({ color: 0x4caf50 }));
scene.add(cube);
renderer.render(scene, cam);
(window as unknown as { __probe: unknown }).__probe = { rev: THREE.REVISION, drawn: true };
